# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calender_update.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)  
        Form.setStyleSheet("background-color: rgb(232, 228, 214);")
        Form.setFixedSize(800, 600)  # Set the fixed size for the whole window
        
        # Calendar Widget
        self.calendarWidget = QtWidgets.QCalendarWidget(Form)
        self.calendarWidget.setGeometry(QtCore.QRect(30, 100, 350, 250))
        self.calendarWidget.setStyleSheet("background-color: rgb(211, 204, 186);")
        self.calendarWidget.setObjectName("calendarWidget")
        
        # Save Button
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(410, 520, 350, 40))  # Wider button
        self.pushButton_2.setStyleSheet("font: 10pt \"MS Gothic\";\n"
"color: rgb(255, 251, 225);\n"
"background-color: #8caa9a")
        self.pushButton_2.setObjectName("pushButton_2")
        
        # Title Label
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 10, 730, 70))  # Wider title bar
        self.label.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";\n"
"font: 36pt \"MS Shell Dlg 2\";\n"
"color: #b9d9ba;\n"
"background-color: #8caa9a;\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        
        # Diary Label (Aligned with Calendar)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(410, 100, 350, 30))  # "DIARY" aligned with Calendar
        self.label_2.setStyleSheet("font: 15pt \"MS Shell Dlg 2\";\n"
"color: #b9d9ba;\n"
"background-color: #8caa9a\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        
        # Diary Text Edit
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(410, 130, 350, 370))        
        self.plainTextEdit_2.setStyleSheet("background-color: rgb(211, 204, 186);")
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        
        # Activities Label (Aligned with Calendar)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 380, 350, 30))  # "ACTIVITIES" aligned with Calendar
        self.label_3.setStyleSheet("font: 15pt \"MS Shell Dlg 2\";\n"
"color: #b9d9ba;\n"
"background-color: #8caa9a\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        
        # Activities Text Edit
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit.setGeometry(QtCore.QRect(30, 410, 350, 150))  # Moved down to align with Activities label
        self.plainTextEdit.setStyleSheet("background-color: rgb(211, 204, 186);")
        self.plainTextEdit.setObjectName("plainTextEdit")
        
        # Raise Elements to make sure they appear on top
        self.calendarWidget.raise_()
        self.label.raise_()
        self.plainTextEdit.raise_()
        self.plainTextEdit_2.raise_()
        self.label_2.raise_()
        self.pushButton_2.raise_()
        self.label_3.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_2.setText(_translate("Form", "Save Changes"))
        self.label.setText(_translate("Form", "CALENDAR"))
        self.label_2.setText(_translate("Form", "DIARY"))
        self.plainTextEdit_2.setPlaceholderText(_translate("Form", "Tell me about your day..."))
        self.label_3.setText(_translate("Form", "ACTIVITIES"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
